// <auto-generated />
namespace PingYourPackage.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_Data_For_Role : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Data_For_Role));
        
        string IMigrationMetadata.Id
        {
            get { return "201804180356263_add_Data_For_Role"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
